import { ASSETS } from './index';

export const VIDEO_URL = [
  `${ASSETS.BRAND_STORY}/1.mp4`,
  `${ASSETS.BRAND_STORY}/2.mp4`,
  `${ASSETS.BRAND_STORY}/3.mp4`,
  `${ASSETS.BRAND_STORY}/4.mp4`,
  `${ASSETS.BRAND_STORY}/5.mp4`,
  `${ASSETS.BRAND_STORY}/6.mp4`,
];

export const THUMBNAILS = [
  `${ASSETS.BRAND_STORY_THUMBNAILS}/1.png`,
  `${ASSETS.BRAND_STORY_THUMBNAILS}/2.png`,
  `${ASSETS.BRAND_STORY_THUMBNAILS}/3.png`,
  `${ASSETS.BRAND_STORY_THUMBNAILS}/4.png`,
  `${ASSETS.BRAND_STORY_THUMBNAILS}/5.png`,
  `${ASSETS.BRAND_STORY_THUMBNAILS}/6.png`,
];
