export const APP_CONSTATNTS = {
  IMAGE_BASE_URL: '/assets',
  SHOPYFY_URL: 'https://dorjeteas.myshopify.com',
};

export const ASSETS = {
  ICONS: `${APP_CONSTATNTS.IMAGE_BASE_URL}/icons`,
  ABOUT_US: `${APP_CONSTATNTS.IMAGE_BASE_URL}/about-us`,
  BANNERS: `${APP_CONSTATNTS.IMAGE_BASE_URL}/banners`,
  BRAND_STORY: `${APP_CONSTATNTS.IMAGE_BASE_URL}/brand-story`,
  BRAND_STORY_THUMBNAILS: `${APP_CONSTATNTS.IMAGE_BASE_URL}/brand-story/thumbnails`,
  BREWING_GUIDE: `${APP_CONSTATNTS.IMAGE_BASE_URL}/brewing-guide`,
  KNOW_YOUR_TEA: `${APP_CONSTATNTS.IMAGE_BASE_URL}/know-your-tea`,
  MAKE_YOUR_OWN_BLEND: `${APP_CONSTATNTS.IMAGE_BASE_URL}/make-your-own-blend`,
  NEW_LAUNCH: `${APP_CONSTATNTS.IMAGE_BASE_URL}/new-launch`,
  SHOP_BY_NEED: `${APP_CONSTATNTS.IMAGE_BASE_URL}/shop-by-need`,
  SHOP_NOW: `${APP_CONSTATNTS.IMAGE_BASE_URL}/shop-now`,
  SVG: `${APP_CONSTATNTS.IMAGE_BASE_URL}/svg`,
  TESTIMONIALS: `${APP_CONSTATNTS.IMAGE_BASE_URL}/testimonials`,
  HOME_PAGE_BANNERS: `${APP_CONSTATNTS.IMAGE_BASE_URL}/home-page-banners`,
  COLLECTION_BENEFITS: `${APP_CONSTATNTS.IMAGE_BASE_URL}/collection-benefits`,
};
